// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: process_proto/01000_01009_login.proto

#ifndef PROTOBUF_process_5fproto_2f01000_5f01009_5flogin_2eproto__INCLUDED
#define PROTOBUF_process_5fproto_2f01000_5f01009_5flogin_2eproto__INCLUDED

#include "pw_iconv.h"
#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2004000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2004001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_message_reflection.h>
#include "pwngs/options.pb.h"
#include "pwngs/protocol/worldsrv/00000_00000_def.pb.h"
// @@protoc_insertion_point(includes)

namespace pwngs {
namespace protocol {
namespace worldsrv {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_process_5fproto_2f01000_5f01009_5flogin_2eproto();
void protobuf_AssignDesc_process_5fproto_2f01000_5f01009_5flogin_2eproto();
void protobuf_ShutdownFile_process_5fproto_2f01000_5f01009_5flogin_2eproto();

class SCharacter;
class CSLoginBegan;
class CSLoginGate;
class SCLoginGate;
class CSQueryCharacters;
class SCQueryCharacters;
class CSCharacterCreate;
class SCCharacterCreate;
class CSCharacterDelete;
class SCCharacterDelete;
class SLadderInformation;
class CSCharacterLogin;
class SServerInformation;
class SCCharacterLogin;
class CSCharacterEnterWorld;
class CSCharacterRevert;
class SCCharacterRevert;
class SCDroppedHumanHint;
class CSKickDroppedHuman;
class CSLoginEnded;

// ===================================================================

class SCharacter : public ::google::protobuf::Message {
 public:
  SCharacter();
  virtual ~SCharacter();
  
  SCharacter(const SCharacter& from);
  
  inline SCharacter& operator=(const SCharacter& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const SCharacter& default_instance();
  
  void Swap(SCharacter* other);
  
  // implements Message ----------------------------------------------
  
  SCharacter* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const SCharacter& from);
  void MergeFrom(const SCharacter& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // required int64 id = 1;
  inline bool has_id() const;
  inline void clear_id();
  static const int kIdFieldNumber = 1;
  inline ::google::protobuf::int64 id() const;
  inline void set_id(::google::protobuf::int64 value);
  
  // required bytes name = 2;
  inline bool has_name() const;
  inline void clear_name();
  static const int kNameFieldNumber = 2;
  inline const ::std::string& name() const;
  inline void set_name(const ::std::string& value);
  inline void set_name(const char* value);
  inline void set_name(const void* value, size_t size);
  inline ::std::string* mutable_name();
  inline ::std::string* release_name();
  inline void name_to_mbs();
  inline void name_to_utf8();
  
  // required int32 profession = 3;
  inline bool has_profession() const;
  inline void clear_profession();
  static const int kProfessionFieldNumber = 3;
  inline ::google::protobuf::int32 profession() const;
  inline void set_profession(::google::protobuf::int32 value);
  
  // required int32 level = 4;
  inline bool has_level() const;
  inline void clear_level();
  static const int kLevelFieldNumber = 4;
  inline ::google::protobuf::int32 level() const;
  inline void set_level(::google::protobuf::int32 value);
  
  // required int32 sex = 5;
  inline bool has_sex() const;
  inline void clear_sex();
  static const int kSexFieldNumber = 5;
  inline ::google::protobuf::int32 sex() const;
  inline void set_sex(::google::protobuf::int32 value);
  
  // required bool newbie = 6;
  inline bool has_newbie() const;
  inline void clear_newbie();
  static const int kNewbieFieldNumber = 6;
  inline bool newbie() const;
  inline void set_newbie(bool value);
  
  // @@protoc_insertion_point(class_scope:pwngs.protocol.worldsrv.SCharacter)
 private:
  inline void set_has_id();
  inline void clear_has_id();
  inline void set_has_name();
  inline void clear_has_name();
  inline void set_has_profession();
  inline void clear_has_profession();
  inline void set_has_level();
  inline void clear_has_level();
  inline void set_has_sex();
  inline void clear_has_sex();
  inline void set_has_newbie();
  inline void clear_has_newbie();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::google::protobuf::int64 id_;
  ::std::string* name_;
  ::google::protobuf::int32 profession_;
  ::google::protobuf::int32 level_;
  ::google::protobuf::int32 sex_;
  bool newbie_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(6 + 31) / 32];
  
  friend void  protobuf_AddDesc_process_5fproto_2f01000_5f01009_5flogin_2eproto();
  friend void protobuf_AssignDesc_process_5fproto_2f01000_5f01009_5flogin_2eproto();
  friend void protobuf_ShutdownFile_process_5fproto_2f01000_5f01009_5flogin_2eproto();
  
  void InitAsDefaultInstance();
  static SCharacter* default_instance_;
};
// -------------------------------------------------------------------

class CSLoginBegan : public ::google::protobuf::Message {
 public:
  CSLoginBegan();
  virtual ~CSLoginBegan();
  
  CSLoginBegan(const CSLoginBegan& from);
  
  inline CSLoginBegan& operator=(const CSLoginBegan& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const CSLoginBegan& default_instance();
  
  void Swap(CSLoginBegan* other);
  
  // implements Message ----------------------------------------------
  
  CSLoginBegan* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const CSLoginBegan& from);
  void MergeFrom(const CSLoginBegan& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // @@protoc_insertion_point(class_scope:pwngs.protocol.worldsrv.CSLoginBegan)
 private:
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[1];
  
  friend void  protobuf_AddDesc_process_5fproto_2f01000_5f01009_5flogin_2eproto();
  friend void protobuf_AssignDesc_process_5fproto_2f01000_5f01009_5flogin_2eproto();
  friend void protobuf_ShutdownFile_process_5fproto_2f01000_5f01009_5flogin_2eproto();
  
  void InitAsDefaultInstance();
  static CSLoginBegan* default_instance_;
};
// -------------------------------------------------------------------

class CSLoginGate : public ::google::protobuf::Message {
 public:
  CSLoginGate();
  virtual ~CSLoginGate();
  
  CSLoginGate(const CSLoginGate& from);
  
  inline CSLoginGate& operator=(const CSLoginGate& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const CSLoginGate& default_instance();
  
  void Swap(CSLoginGate* other);
  
  // implements Message ----------------------------------------------
  
  CSLoginGate* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const CSLoginGate& from);
  void MergeFrom(const CSLoginGate& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // @@protoc_insertion_point(class_scope:pwngs.protocol.worldsrv.CSLoginGate)
 private:
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[1];
  
  friend void  protobuf_AddDesc_process_5fproto_2f01000_5f01009_5flogin_2eproto();
  friend void protobuf_AssignDesc_process_5fproto_2f01000_5f01009_5flogin_2eproto();
  friend void protobuf_ShutdownFile_process_5fproto_2f01000_5f01009_5flogin_2eproto();
  
  void InitAsDefaultInstance();
  static CSLoginGate* default_instance_;
};
// -------------------------------------------------------------------

class SCLoginGate : public ::google::protobuf::Message {
 public:
  SCLoginGate();
  virtual ~SCLoginGate();
  
  SCLoginGate(const SCLoginGate& from);
  
  inline SCLoginGate& operator=(const SCLoginGate& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const SCLoginGate& default_instance();
  
  void Swap(SCLoginGate* other);
  
  // implements Message ----------------------------------------------
  
  SCLoginGate* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const SCLoginGate& from);
  void MergeFrom(const SCLoginGate& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // required int32 result = 1;
  inline bool has_result() const;
  inline void clear_result();
  static const int kResultFieldNumber = 1;
  inline ::google::protobuf::int32 result() const;
  inline void set_result(::google::protobuf::int32 value);
  
  // @@protoc_insertion_point(class_scope:pwngs.protocol.worldsrv.SCLoginGate)
 private:
  inline void set_has_result();
  inline void clear_has_result();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::google::protobuf::int32 result_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];
  
  friend void  protobuf_AddDesc_process_5fproto_2f01000_5f01009_5flogin_2eproto();
  friend void protobuf_AssignDesc_process_5fproto_2f01000_5f01009_5flogin_2eproto();
  friend void protobuf_ShutdownFile_process_5fproto_2f01000_5f01009_5flogin_2eproto();
  
  void InitAsDefaultInstance();
  static SCLoginGate* default_instance_;
};
// -------------------------------------------------------------------

class CSQueryCharacters : public ::google::protobuf::Message {
 public:
  CSQueryCharacters();
  virtual ~CSQueryCharacters();
  
  CSQueryCharacters(const CSQueryCharacters& from);
  
  inline CSQueryCharacters& operator=(const CSQueryCharacters& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const CSQueryCharacters& default_instance();
  
  void Swap(CSQueryCharacters* other);
  
  // implements Message ----------------------------------------------
  
  CSQueryCharacters* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const CSQueryCharacters& from);
  void MergeFrom(const CSQueryCharacters& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // @@protoc_insertion_point(class_scope:pwngs.protocol.worldsrv.CSQueryCharacters)
 private:
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[1];
  
  friend void  protobuf_AddDesc_process_5fproto_2f01000_5f01009_5flogin_2eproto();
  friend void protobuf_AssignDesc_process_5fproto_2f01000_5f01009_5flogin_2eproto();
  friend void protobuf_ShutdownFile_process_5fproto_2f01000_5f01009_5flogin_2eproto();
  
  void InitAsDefaultInstance();
  static CSQueryCharacters* default_instance_;
};
// -------------------------------------------------------------------

class SCQueryCharacters : public ::google::protobuf::Message {
 public:
  SCQueryCharacters();
  virtual ~SCQueryCharacters();
  
  SCQueryCharacters(const SCQueryCharacters& from);
  
  inline SCQueryCharacters& operator=(const SCQueryCharacters& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const SCQueryCharacters& default_instance();
  
  void Swap(SCQueryCharacters* other);
  
  // implements Message ----------------------------------------------
  
  SCQueryCharacters* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const SCQueryCharacters& from);
  void MergeFrom(const SCQueryCharacters& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // repeated .pwngs.protocol.worldsrv.SCharacter characters = 1;
  inline int characters_size() const;
  inline void clear_characters();
  static const int kCharactersFieldNumber = 1;
  inline const ::pwngs::protocol::worldsrv::SCharacter& characters(int index) const;
  inline ::pwngs::protocol::worldsrv::SCharacter* mutable_characters(int index);
  inline ::pwngs::protocol::worldsrv::SCharacter* add_characters();
  inline const ::google::protobuf::RepeatedPtrField< ::pwngs::protocol::worldsrv::SCharacter >&
      characters() const;
  inline ::google::protobuf::RepeatedPtrField< ::pwngs::protocol::worldsrv::SCharacter >*
      mutable_characters();
  
  // optional int64 last_login_hid = 2;
  inline bool has_last_login_hid() const;
  inline void clear_last_login_hid();
  static const int kLastLoginHidFieldNumber = 2;
  inline ::google::protobuf::int64 last_login_hid() const;
  inline void set_last_login_hid(::google::protobuf::int64 value);
  
  // @@protoc_insertion_point(class_scope:pwngs.protocol.worldsrv.SCQueryCharacters)
 private:
  inline void set_has_last_login_hid();
  inline void clear_has_last_login_hid();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::google::protobuf::RepeatedPtrField< ::pwngs::protocol::worldsrv::SCharacter > characters_;
  ::google::protobuf::int64 last_login_hid_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];
  
  friend void  protobuf_AddDesc_process_5fproto_2f01000_5f01009_5flogin_2eproto();
  friend void protobuf_AssignDesc_process_5fproto_2f01000_5f01009_5flogin_2eproto();
  friend void protobuf_ShutdownFile_process_5fproto_2f01000_5f01009_5flogin_2eproto();
  
  void InitAsDefaultInstance();
  static SCQueryCharacters* default_instance_;
};
// -------------------------------------------------------------------

class CSCharacterCreate : public ::google::protobuf::Message {
 public:
  CSCharacterCreate();
  virtual ~CSCharacterCreate();
  
  CSCharacterCreate(const CSCharacterCreate& from);
  
  inline CSCharacterCreate& operator=(const CSCharacterCreate& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const CSCharacterCreate& default_instance();
  
  void Swap(CSCharacterCreate* other);
  
  // implements Message ----------------------------------------------
  
  CSCharacterCreate* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const CSCharacterCreate& from);
  void MergeFrom(const CSCharacterCreate& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // required bytes name = 1;
  inline bool has_name() const;
  inline void clear_name();
  static const int kNameFieldNumber = 1;
  inline const ::std::string& name() const;
  inline void set_name(const ::std::string& value);
  inline void set_name(const char* value);
  inline void set_name(const void* value, size_t size);
  inline ::std::string* mutable_name();
  inline ::std::string* release_name();
  inline void name_to_mbs();
  inline void name_to_utf8();
  
  // required int32 profession = 2;
  inline bool has_profession() const;
  inline void clear_profession();
  static const int kProfessionFieldNumber = 2;
  inline ::google::protobuf::int32 profession() const;
  inline void set_profession(::google::protobuf::int32 value);
  
  // required int32 sex = 3;
  inline bool has_sex() const;
  inline void clear_sex();
  static const int kSexFieldNumber = 3;
  inline ::google::protobuf::int32 sex() const;
  inline void set_sex(::google::protobuf::int32 value);
  
  // @@protoc_insertion_point(class_scope:pwngs.protocol.worldsrv.CSCharacterCreate)
 private:
  inline void set_has_name();
  inline void clear_has_name();
  inline void set_has_profession();
  inline void clear_has_profession();
  inline void set_has_sex();
  inline void clear_has_sex();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::std::string* name_;
  ::google::protobuf::int32 profession_;
  ::google::protobuf::int32 sex_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(3 + 31) / 32];
  
  friend void  protobuf_AddDesc_process_5fproto_2f01000_5f01009_5flogin_2eproto();
  friend void protobuf_AssignDesc_process_5fproto_2f01000_5f01009_5flogin_2eproto();
  friend void protobuf_ShutdownFile_process_5fproto_2f01000_5f01009_5flogin_2eproto();
  
  void InitAsDefaultInstance();
  static CSCharacterCreate* default_instance_;
};
// -------------------------------------------------------------------

class SCCharacterCreate : public ::google::protobuf::Message {
 public:
  SCCharacterCreate();
  virtual ~SCCharacterCreate();
  
  SCCharacterCreate(const SCCharacterCreate& from);
  
  inline SCCharacterCreate& operator=(const SCCharacterCreate& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const SCCharacterCreate& default_instance();
  
  void Swap(SCCharacterCreate* other);
  
  // implements Message ----------------------------------------------
  
  SCCharacterCreate* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const SCCharacterCreate& from);
  void MergeFrom(const SCCharacterCreate& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // required int32 result = 1;
  inline bool has_result() const;
  inline void clear_result();
  static const int kResultFieldNumber = 1;
  inline ::google::protobuf::int32 result() const;
  inline void set_result(::google::protobuf::int32 value);
  
  // optional .pwngs.protocol.worldsrv.SCharacter character = 2;
  inline bool has_character() const;
  inline void clear_character();
  static const int kCharacterFieldNumber = 2;
  inline const ::pwngs::protocol::worldsrv::SCharacter& character() const;
  inline ::pwngs::protocol::worldsrv::SCharacter* mutable_character();
  inline ::pwngs::protocol::worldsrv::SCharacter* release_character();
  
  // @@protoc_insertion_point(class_scope:pwngs.protocol.worldsrv.SCCharacterCreate)
 private:
  inline void set_has_result();
  inline void clear_has_result();
  inline void set_has_character();
  inline void clear_has_character();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::pwngs::protocol::worldsrv::SCharacter* character_;
  ::google::protobuf::int32 result_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];
  
  friend void  protobuf_AddDesc_process_5fproto_2f01000_5f01009_5flogin_2eproto();
  friend void protobuf_AssignDesc_process_5fproto_2f01000_5f01009_5flogin_2eproto();
  friend void protobuf_ShutdownFile_process_5fproto_2f01000_5f01009_5flogin_2eproto();
  
  void InitAsDefaultInstance();
  static SCCharacterCreate* default_instance_;
};
// -------------------------------------------------------------------

class CSCharacterDelete : public ::google::protobuf::Message {
 public:
  CSCharacterDelete();
  virtual ~CSCharacterDelete();
  
  CSCharacterDelete(const CSCharacterDelete& from);
  
  inline CSCharacterDelete& operator=(const CSCharacterDelete& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const CSCharacterDelete& default_instance();
  
  void Swap(CSCharacterDelete* other);
  
  // implements Message ----------------------------------------------
  
  CSCharacterDelete* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const CSCharacterDelete& from);
  void MergeFrom(const CSCharacterDelete& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // required int64 id = 1;
  inline bool has_id() const;
  inline void clear_id();
  static const int kIdFieldNumber = 1;
  inline ::google::protobuf::int64 id() const;
  inline void set_id(::google::protobuf::int64 value);
  
  // @@protoc_insertion_point(class_scope:pwngs.protocol.worldsrv.CSCharacterDelete)
 private:
  inline void set_has_id();
  inline void clear_has_id();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::google::protobuf::int64 id_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];
  
  friend void  protobuf_AddDesc_process_5fproto_2f01000_5f01009_5flogin_2eproto();
  friend void protobuf_AssignDesc_process_5fproto_2f01000_5f01009_5flogin_2eproto();
  friend void protobuf_ShutdownFile_process_5fproto_2f01000_5f01009_5flogin_2eproto();
  
  void InitAsDefaultInstance();
  static CSCharacterDelete* default_instance_;
};
// -------------------------------------------------------------------

class SCCharacterDelete : public ::google::protobuf::Message {
 public:
  SCCharacterDelete();
  virtual ~SCCharacterDelete();
  
  SCCharacterDelete(const SCCharacterDelete& from);
  
  inline SCCharacterDelete& operator=(const SCCharacterDelete& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const SCCharacterDelete& default_instance();
  
  void Swap(SCCharacterDelete* other);
  
  // implements Message ----------------------------------------------
  
  SCCharacterDelete* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const SCCharacterDelete& from);
  void MergeFrom(const SCCharacterDelete& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // required int32 result = 1;
  inline bool has_result() const;
  inline void clear_result();
  static const int kResultFieldNumber = 1;
  inline ::google::protobuf::int32 result() const;
  inline void set_result(::google::protobuf::int32 value);
  
  // optional int64 id = 2;
  inline bool has_id() const;
  inline void clear_id();
  static const int kIdFieldNumber = 2;
  inline ::google::protobuf::int64 id() const;
  inline void set_id(::google::protobuf::int64 value);
  
  // optional int64 survive_time = 3;
  inline bool has_survive_time() const;
  inline void clear_survive_time();
  static const int kSurviveTimeFieldNumber = 3;
  inline ::google::protobuf::int64 survive_time() const;
  inline void set_survive_time(::google::protobuf::int64 value);
  
  // @@protoc_insertion_point(class_scope:pwngs.protocol.worldsrv.SCCharacterDelete)
 private:
  inline void set_has_result();
  inline void clear_has_result();
  inline void set_has_id();
  inline void clear_has_id();
  inline void set_has_survive_time();
  inline void clear_has_survive_time();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::google::protobuf::int64 id_;
  ::google::protobuf::int64 survive_time_;
  ::google::protobuf::int32 result_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(3 + 31) / 32];
  
  friend void  protobuf_AddDesc_process_5fproto_2f01000_5f01009_5flogin_2eproto();
  friend void protobuf_AssignDesc_process_5fproto_2f01000_5f01009_5flogin_2eproto();
  friend void protobuf_ShutdownFile_process_5fproto_2f01000_5f01009_5flogin_2eproto();
  
  void InitAsDefaultInstance();
  static SCCharacterDelete* default_instance_;
};
// -------------------------------------------------------------------

class SLadderInformation : public ::google::protobuf::Message {
 public:
  SLadderInformation();
  virtual ~SLadderInformation();
  
  SLadderInformation(const SLadderInformation& from);
  
  inline SLadderInformation& operator=(const SLadderInformation& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const SLadderInformation& default_instance();
  
  void Swap(SLadderInformation* other);
  
  // implements Message ----------------------------------------------
  
  SLadderInformation* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const SLadderInformation& from);
  void MergeFrom(const SLadderInformation& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // required int32 basemap = 1;
  inline bool has_basemap() const;
  inline void clear_basemap();
  static const int kBasemapFieldNumber = 1;
  inline ::google::protobuf::int32 basemap() const;
  inline void set_basemap(::google::protobuf::int32 value);
  
  // required int64 gamemap = 2;
  inline bool has_gamemap() const;
  inline void clear_gamemap();
  static const int kGamemapFieldNumber = 2;
  inline ::google::protobuf::int64 gamemap() const;
  inline void set_gamemap(::google::protobuf::int64 value);
  
  // @@protoc_insertion_point(class_scope:pwngs.protocol.worldsrv.SLadderInformation)
 private:
  inline void set_has_basemap();
  inline void clear_has_basemap();
  inline void set_has_gamemap();
  inline void clear_has_gamemap();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::google::protobuf::int64 gamemap_;
  ::google::protobuf::int32 basemap_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];
  
  friend void  protobuf_AddDesc_process_5fproto_2f01000_5f01009_5flogin_2eproto();
  friend void protobuf_AssignDesc_process_5fproto_2f01000_5f01009_5flogin_2eproto();
  friend void protobuf_ShutdownFile_process_5fproto_2f01000_5f01009_5flogin_2eproto();
  
  void InitAsDefaultInstance();
  static SLadderInformation* default_instance_;
};
// -------------------------------------------------------------------

class CSCharacterLogin : public ::google::protobuf::Message {
 public:
  CSCharacterLogin();
  virtual ~CSCharacterLogin();
  
  CSCharacterLogin(const CSCharacterLogin& from);
  
  inline CSCharacterLogin& operator=(const CSCharacterLogin& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const CSCharacterLogin& default_instance();
  
  void Swap(CSCharacterLogin* other);
  
  // implements Message ----------------------------------------------
  
  CSCharacterLogin* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const CSCharacterLogin& from);
  void MergeFrom(const CSCharacterLogin& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // required int64 cid = 1;
  inline bool has_cid() const;
  inline void clear_cid();
  static const int kCidFieldNumber = 1;
  inline ::google::protobuf::int64 cid() const;
  inline void set_cid(::google::protobuf::int64 value);
  
  // optional bytes mac = 2;
  inline bool has_mac() const;
  inline void clear_mac();
  static const int kMacFieldNumber = 2;
  inline const ::std::string& mac() const;
  inline void set_mac(const ::std::string& value);
  inline void set_mac(const char* value);
  inline void set_mac(const void* value, size_t size);
  inline ::std::string* mutable_mac();
  inline ::std::string* release_mac();
  inline void mac_to_mbs();
  inline void mac_to_utf8();
  
  // optional .pwngs.protocol.worldsrv.SLadderInformation ladder_info = 3;
  inline bool has_ladder_info() const;
  inline void clear_ladder_info();
  static const int kLadderInfoFieldNumber = 3;
  inline const ::pwngs::protocol::worldsrv::SLadderInformation& ladder_info() const;
  inline ::pwngs::protocol::worldsrv::SLadderInformation* mutable_ladder_info();
  inline ::pwngs::protocol::worldsrv::SLadderInformation* release_ladder_info();
  
  // @@protoc_insertion_point(class_scope:pwngs.protocol.worldsrv.CSCharacterLogin)
 private:
  inline void set_has_cid();
  inline void clear_has_cid();
  inline void set_has_mac();
  inline void clear_has_mac();
  inline void set_has_ladder_info();
  inline void clear_has_ladder_info();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::google::protobuf::int64 cid_;
  ::std::string* mac_;
  ::pwngs::protocol::worldsrv::SLadderInformation* ladder_info_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(3 + 31) / 32];
  
  friend void  protobuf_AddDesc_process_5fproto_2f01000_5f01009_5flogin_2eproto();
  friend void protobuf_AssignDesc_process_5fproto_2f01000_5f01009_5flogin_2eproto();
  friend void protobuf_ShutdownFile_process_5fproto_2f01000_5f01009_5flogin_2eproto();
  
  void InitAsDefaultInstance();
  static CSCharacterLogin* default_instance_;
};
// -------------------------------------------------------------------

class SServerInformation : public ::google::protobuf::Message {
 public:
  SServerInformation();
  virtual ~SServerInformation();
  
  SServerInformation(const SServerInformation& from);
  
  inline SServerInformation& operator=(const SServerInformation& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const SServerInformation& default_instance();
  
  void Swap(SServerInformation* other);
  
  // implements Message ----------------------------------------------
  
  SServerInformation* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const SServerInformation& from);
  void MergeFrom(const SServerInformation& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // required int64 zone_id = 1;
  inline bool has_zone_id() const;
  inline void clear_zone_id();
  static const int kZoneIdFieldNumber = 1;
  inline ::google::protobuf::int64 zone_id() const;
  inline void set_zone_id(::google::protobuf::int64 value);
  
  // required bytes operators_name = 2;
  inline bool has_operators_name() const;
  inline void clear_operators_name();
  static const int kOperatorsNameFieldNumber = 2;
  inline const ::std::string& operators_name() const;
  inline void set_operators_name(const ::std::string& value);
  inline void set_operators_name(const char* value);
  inline void set_operators_name(const void* value, size_t size);
  inline ::std::string* mutable_operators_name();
  inline ::std::string* release_operators_name();
  inline void operators_name_to_mbs();
  inline void operators_name_to_utf8();
  
  // @@protoc_insertion_point(class_scope:pwngs.protocol.worldsrv.SServerInformation)
 private:
  inline void set_has_zone_id();
  inline void clear_has_zone_id();
  inline void set_has_operators_name();
  inline void clear_has_operators_name();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::google::protobuf::int64 zone_id_;
  ::std::string* operators_name_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];
  
  friend void  protobuf_AddDesc_process_5fproto_2f01000_5f01009_5flogin_2eproto();
  friend void protobuf_AssignDesc_process_5fproto_2f01000_5f01009_5flogin_2eproto();
  friend void protobuf_ShutdownFile_process_5fproto_2f01000_5f01009_5flogin_2eproto();
  
  void InitAsDefaultInstance();
  static SServerInformation* default_instance_;
};
// -------------------------------------------------------------------

class SCCharacterLogin : public ::google::protobuf::Message {
 public:
  SCCharacterLogin();
  virtual ~SCCharacterLogin();
  
  SCCharacterLogin(const SCCharacterLogin& from);
  
  inline SCCharacterLogin& operator=(const SCCharacterLogin& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const SCCharacterLogin& default_instance();
  
  void Swap(SCCharacterLogin* other);
  
  // implements Message ----------------------------------------------
  
  SCCharacterLogin* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const SCCharacterLogin& from);
  void MergeFrom(const SCCharacterLogin& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // required int32 result = 1;
  inline bool has_result() const;
  inline void clear_result();
  static const int kResultFieldNumber = 1;
  inline ::google::protobuf::int32 result() const;
  inline void set_result(::google::protobuf::int32 value);
  
  // optional bytes error = 2;
  inline bool has_error() const;
  inline void clear_error();
  static const int kErrorFieldNumber = 2;
  inline const ::std::string& error() const;
  inline void set_error(const ::std::string& value);
  inline void set_error(const char* value);
  inline void set_error(const void* value, size_t size);
  inline ::std::string* mutable_error();
  inline ::std::string* release_error();
  inline void error_to_mbs();
  inline void error_to_utf8();
  
  // @@protoc_insertion_point(class_scope:pwngs.protocol.worldsrv.SCCharacterLogin)
 private:
  inline void set_has_result();
  inline void clear_has_result();
  inline void set_has_error();
  inline void clear_has_error();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::std::string* error_;
  ::google::protobuf::int32 result_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];
  
  friend void  protobuf_AddDesc_process_5fproto_2f01000_5f01009_5flogin_2eproto();
  friend void protobuf_AssignDesc_process_5fproto_2f01000_5f01009_5flogin_2eproto();
  friend void protobuf_ShutdownFile_process_5fproto_2f01000_5f01009_5flogin_2eproto();
  
  void InitAsDefaultInstance();
  static SCCharacterLogin* default_instance_;
};
// -------------------------------------------------------------------

class CSCharacterEnterWorld : public ::google::protobuf::Message {
 public:
  CSCharacterEnterWorld();
  virtual ~CSCharacterEnterWorld();
  
  CSCharacterEnterWorld(const CSCharacterEnterWorld& from);
  
  inline CSCharacterEnterWorld& operator=(const CSCharacterEnterWorld& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const CSCharacterEnterWorld& default_instance();
  
  void Swap(CSCharacterEnterWorld* other);
  
  // implements Message ----------------------------------------------
  
  CSCharacterEnterWorld* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const CSCharacterEnterWorld& from);
  void MergeFrom(const CSCharacterEnterWorld& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // required int64 id = 1;
  inline bool has_id() const;
  inline void clear_id();
  static const int kIdFieldNumber = 1;
  inline ::google::protobuf::int64 id() const;
  inline void set_id(::google::protobuf::int64 value);
  
  // @@protoc_insertion_point(class_scope:pwngs.protocol.worldsrv.CSCharacterEnterWorld)
 private:
  inline void set_has_id();
  inline void clear_has_id();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::google::protobuf::int64 id_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];
  
  friend void  protobuf_AddDesc_process_5fproto_2f01000_5f01009_5flogin_2eproto();
  friend void protobuf_AssignDesc_process_5fproto_2f01000_5f01009_5flogin_2eproto();
  friend void protobuf_ShutdownFile_process_5fproto_2f01000_5f01009_5flogin_2eproto();
  
  void InitAsDefaultInstance();
  static CSCharacterEnterWorld* default_instance_;
};
// -------------------------------------------------------------------

class CSCharacterRevert : public ::google::protobuf::Message {
 public:
  CSCharacterRevert();
  virtual ~CSCharacterRevert();
  
  CSCharacterRevert(const CSCharacterRevert& from);
  
  inline CSCharacterRevert& operator=(const CSCharacterRevert& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const CSCharacterRevert& default_instance();
  
  void Swap(CSCharacterRevert* other);
  
  // implements Message ----------------------------------------------
  
  CSCharacterRevert* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const CSCharacterRevert& from);
  void MergeFrom(const CSCharacterRevert& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // required int64 id = 1;
  inline bool has_id() const;
  inline void clear_id();
  static const int kIdFieldNumber = 1;
  inline ::google::protobuf::int64 id() const;
  inline void set_id(::google::protobuf::int64 value);
  
  // @@protoc_insertion_point(class_scope:pwngs.protocol.worldsrv.CSCharacterRevert)
 private:
  inline void set_has_id();
  inline void clear_has_id();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::google::protobuf::int64 id_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];
  
  friend void  protobuf_AddDesc_process_5fproto_2f01000_5f01009_5flogin_2eproto();
  friend void protobuf_AssignDesc_process_5fproto_2f01000_5f01009_5flogin_2eproto();
  friend void protobuf_ShutdownFile_process_5fproto_2f01000_5f01009_5flogin_2eproto();
  
  void InitAsDefaultInstance();
  static CSCharacterRevert* default_instance_;
};
// -------------------------------------------------------------------

class SCCharacterRevert : public ::google::protobuf::Message {
 public:
  SCCharacterRevert();
  virtual ~SCCharacterRevert();
  
  SCCharacterRevert(const SCCharacterRevert& from);
  
  inline SCCharacterRevert& operator=(const SCCharacterRevert& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const SCCharacterRevert& default_instance();
  
  void Swap(SCCharacterRevert* other);
  
  // implements Message ----------------------------------------------
  
  SCCharacterRevert* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const SCCharacterRevert& from);
  void MergeFrom(const SCCharacterRevert& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // required int32 result = 1;
  inline bool has_result() const;
  inline void clear_result();
  static const int kResultFieldNumber = 1;
  inline ::google::protobuf::int32 result() const;
  inline void set_result(::google::protobuf::int32 value);
  
  // optional int64 id = 2;
  inline bool has_id() const;
  inline void clear_id();
  static const int kIdFieldNumber = 2;
  inline ::google::protobuf::int64 id() const;
  inline void set_id(::google::protobuf::int64 value);
  
  // @@protoc_insertion_point(class_scope:pwngs.protocol.worldsrv.SCCharacterRevert)
 private:
  inline void set_has_result();
  inline void clear_has_result();
  inline void set_has_id();
  inline void clear_has_id();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::google::protobuf::int64 id_;
  ::google::protobuf::int32 result_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];
  
  friend void  protobuf_AddDesc_process_5fproto_2f01000_5f01009_5flogin_2eproto();
  friend void protobuf_AssignDesc_process_5fproto_2f01000_5f01009_5flogin_2eproto();
  friend void protobuf_ShutdownFile_process_5fproto_2f01000_5f01009_5flogin_2eproto();
  
  void InitAsDefaultInstance();
  static SCCharacterRevert* default_instance_;
};
// -------------------------------------------------------------------

class SCDroppedHumanHint : public ::google::protobuf::Message {
 public:
  SCDroppedHumanHint();
  virtual ~SCDroppedHumanHint();
  
  SCDroppedHumanHint(const SCDroppedHumanHint& from);
  
  inline SCDroppedHumanHint& operator=(const SCDroppedHumanHint& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const SCDroppedHumanHint& default_instance();
  
  void Swap(SCDroppedHumanHint* other);
  
  // implements Message ----------------------------------------------
  
  SCDroppedHumanHint* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const SCDroppedHumanHint& from);
  void MergeFrom(const SCDroppedHumanHint& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // required int64 dropped_hid = 1;
  inline bool has_dropped_hid() const;
  inline void clear_dropped_hid();
  static const int kDroppedHidFieldNumber = 1;
  inline ::google::protobuf::int64 dropped_hid() const;
  inline void set_dropped_hid(::google::protobuf::int64 value);
  
  // required int32 dropped_scene = 2;
  inline bool has_dropped_scene() const;
  inline void clear_dropped_scene();
  static const int kDroppedSceneFieldNumber = 2;
  inline ::google::protobuf::int32 dropped_scene() const;
  inline void set_dropped_scene(::google::protobuf::int32 value);
  
  // required int64 request_hid = 3;
  inline bool has_request_hid() const;
  inline void clear_request_hid();
  static const int kRequestHidFieldNumber = 3;
  inline ::google::protobuf::int64 request_hid() const;
  inline void set_request_hid(::google::protobuf::int64 value);
  
  // @@protoc_insertion_point(class_scope:pwngs.protocol.worldsrv.SCDroppedHumanHint)
 private:
  inline void set_has_dropped_hid();
  inline void clear_has_dropped_hid();
  inline void set_has_dropped_scene();
  inline void clear_has_dropped_scene();
  inline void set_has_request_hid();
  inline void clear_has_request_hid();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::google::protobuf::int64 dropped_hid_;
  ::google::protobuf::int64 request_hid_;
  ::google::protobuf::int32 dropped_scene_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(3 + 31) / 32];
  
  friend void  protobuf_AddDesc_process_5fproto_2f01000_5f01009_5flogin_2eproto();
  friend void protobuf_AssignDesc_process_5fproto_2f01000_5f01009_5flogin_2eproto();
  friend void protobuf_ShutdownFile_process_5fproto_2f01000_5f01009_5flogin_2eproto();
  
  void InitAsDefaultInstance();
  static SCDroppedHumanHint* default_instance_;
};
// -------------------------------------------------------------------

class CSKickDroppedHuman : public ::google::protobuf::Message {
 public:
  CSKickDroppedHuman();
  virtual ~CSKickDroppedHuman();
  
  CSKickDroppedHuman(const CSKickDroppedHuman& from);
  
  inline CSKickDroppedHuman& operator=(const CSKickDroppedHuman& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const CSKickDroppedHuman& default_instance();
  
  void Swap(CSKickDroppedHuman* other);
  
  // implements Message ----------------------------------------------
  
  CSKickDroppedHuman* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const CSKickDroppedHuman& from);
  void MergeFrom(const CSKickDroppedHuman& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // @@protoc_insertion_point(class_scope:pwngs.protocol.worldsrv.CSKickDroppedHuman)
 private:
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[1];
  
  friend void  protobuf_AddDesc_process_5fproto_2f01000_5f01009_5flogin_2eproto();
  friend void protobuf_AssignDesc_process_5fproto_2f01000_5f01009_5flogin_2eproto();
  friend void protobuf_ShutdownFile_process_5fproto_2f01000_5f01009_5flogin_2eproto();
  
  void InitAsDefaultInstance();
  static CSKickDroppedHuman* default_instance_;
};
// -------------------------------------------------------------------

class CSLoginEnded : public ::google::protobuf::Message {
 public:
  CSLoginEnded();
  virtual ~CSLoginEnded();
  
  CSLoginEnded(const CSLoginEnded& from);
  
  inline CSLoginEnded& operator=(const CSLoginEnded& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const CSLoginEnded& default_instance();
  
  void Swap(CSLoginEnded* other);
  
  // implements Message ----------------------------------------------
  
  CSLoginEnded* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const CSLoginEnded& from);
  void MergeFrom(const CSLoginEnded& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // @@protoc_insertion_point(class_scope:pwngs.protocol.worldsrv.CSLoginEnded)
 private:
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[1];
  
  friend void  protobuf_AddDesc_process_5fproto_2f01000_5f01009_5flogin_2eproto();
  friend void protobuf_AssignDesc_process_5fproto_2f01000_5f01009_5flogin_2eproto();
  friend void protobuf_ShutdownFile_process_5fproto_2f01000_5f01009_5flogin_2eproto();
  
  void InitAsDefaultInstance();
  static CSLoginEnded* default_instance_;
};
// ===================================================================


// ===================================================================

// SCharacter

// required int64 id = 1;
inline bool SCharacter::has_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void SCharacter::set_has_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void SCharacter::clear_has_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void SCharacter::clear_id() {
  id_ = GOOGLE_LONGLONG(0);
  clear_has_id();
}
inline ::google::protobuf::int64 SCharacter::id() const {
  return id_;
}
inline void SCharacter::set_id(::google::protobuf::int64 value) {
  set_has_id();
  id_ = value;
}

// required bytes name = 2;
inline bool SCharacter::has_name() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void SCharacter::set_has_name() {
  _has_bits_[0] |= 0x00000002u;
}
inline void SCharacter::clear_has_name() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void SCharacter::clear_name() {
  if (name_ != &::google::protobuf::internal::kEmptyString) {
    name_->clear();
  }
  clear_has_name();
}
inline void SCharacter::name_to_mbs() {
*name_ = pwutils::utf8_to_mbs(*name_);
}
inline void SCharacter::name_to_utf8() {
*name_ = pwutils::utf8_from_mbs(*name_);
}
inline const ::std::string& SCharacter::name() const {
  return *name_;
}
inline void SCharacter::set_name(const ::std::string& value) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    name_ = new ::std::string;
  }
  name_->assign(value);
}
inline void SCharacter::set_name(const char* value) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    name_ = new ::std::string;
  }
  name_->assign(value);
}
inline void SCharacter::set_name(const void* value, size_t size) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    name_ = new ::std::string;
  }
  name_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* SCharacter::mutable_name() {
  set_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    name_ = new ::std::string;
  }
  return name_;
}
inline ::std::string* SCharacter::release_name() {
  clear_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = name_;
    name_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}

// required int32 profession = 3;
inline bool SCharacter::has_profession() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void SCharacter::set_has_profession() {
  _has_bits_[0] |= 0x00000004u;
}
inline void SCharacter::clear_has_profession() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void SCharacter::clear_profession() {
  profession_ = 0;
  clear_has_profession();
}
inline ::google::protobuf::int32 SCharacter::profession() const {
  return profession_;
}
inline void SCharacter::set_profession(::google::protobuf::int32 value) {
  set_has_profession();
  profession_ = value;
}

// required int32 level = 4;
inline bool SCharacter::has_level() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void SCharacter::set_has_level() {
  _has_bits_[0] |= 0x00000008u;
}
inline void SCharacter::clear_has_level() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void SCharacter::clear_level() {
  level_ = 0;
  clear_has_level();
}
inline ::google::protobuf::int32 SCharacter::level() const {
  return level_;
}
inline void SCharacter::set_level(::google::protobuf::int32 value) {
  set_has_level();
  level_ = value;
}

// required int32 sex = 5;
inline bool SCharacter::has_sex() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void SCharacter::set_has_sex() {
  _has_bits_[0] |= 0x00000010u;
}
inline void SCharacter::clear_has_sex() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void SCharacter::clear_sex() {
  sex_ = 0;
  clear_has_sex();
}
inline ::google::protobuf::int32 SCharacter::sex() const {
  return sex_;
}
inline void SCharacter::set_sex(::google::protobuf::int32 value) {
  set_has_sex();
  sex_ = value;
}

// required bool newbie = 6;
inline bool SCharacter::has_newbie() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void SCharacter::set_has_newbie() {
  _has_bits_[0] |= 0x00000020u;
}
inline void SCharacter::clear_has_newbie() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void SCharacter::clear_newbie() {
  newbie_ = false;
  clear_has_newbie();
}
inline bool SCharacter::newbie() const {
  return newbie_;
}
inline void SCharacter::set_newbie(bool value) {
  set_has_newbie();
  newbie_ = value;
}

// -------------------------------------------------------------------

// CSLoginBegan

// -------------------------------------------------------------------

// CSLoginGate

// -------------------------------------------------------------------

// SCLoginGate

// required int32 result = 1;
inline bool SCLoginGate::has_result() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void SCLoginGate::set_has_result() {
  _has_bits_[0] |= 0x00000001u;
}
inline void SCLoginGate::clear_has_result() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void SCLoginGate::clear_result() {
  result_ = 0;
  clear_has_result();
}
inline ::google::protobuf::int32 SCLoginGate::result() const {
  return result_;
}
inline void SCLoginGate::set_result(::google::protobuf::int32 value) {
  set_has_result();
  result_ = value;
}

// -------------------------------------------------------------------

// CSQueryCharacters

// -------------------------------------------------------------------

// SCQueryCharacters

// repeated .pwngs.protocol.worldsrv.SCharacter characters = 1;
inline int SCQueryCharacters::characters_size() const {
  return characters_.size();
}
inline void SCQueryCharacters::clear_characters() {
  characters_.Clear();
}
inline const ::pwngs::protocol::worldsrv::SCharacter& SCQueryCharacters::characters(int index) const {
  return characters_.Get(index);
}
inline ::pwngs::protocol::worldsrv::SCharacter* SCQueryCharacters::mutable_characters(int index) {
  return characters_.Mutable(index);
}
inline ::pwngs::protocol::worldsrv::SCharacter* SCQueryCharacters::add_characters() {
  return characters_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::pwngs::protocol::worldsrv::SCharacter >&
SCQueryCharacters::characters() const {
  return characters_;
}
inline ::google::protobuf::RepeatedPtrField< ::pwngs::protocol::worldsrv::SCharacter >*
SCQueryCharacters::mutable_characters() {
  return &characters_;
}

// optional int64 last_login_hid = 2;
inline bool SCQueryCharacters::has_last_login_hid() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void SCQueryCharacters::set_has_last_login_hid() {
  _has_bits_[0] |= 0x00000002u;
}
inline void SCQueryCharacters::clear_has_last_login_hid() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void SCQueryCharacters::clear_last_login_hid() {
  last_login_hid_ = GOOGLE_LONGLONG(0);
  clear_has_last_login_hid();
}
inline ::google::protobuf::int64 SCQueryCharacters::last_login_hid() const {
  return last_login_hid_;
}
inline void SCQueryCharacters::set_last_login_hid(::google::protobuf::int64 value) {
  set_has_last_login_hid();
  last_login_hid_ = value;
}

// -------------------------------------------------------------------

// CSCharacterCreate

// required bytes name = 1;
inline bool CSCharacterCreate::has_name() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void CSCharacterCreate::set_has_name() {
  _has_bits_[0] |= 0x00000001u;
}
inline void CSCharacterCreate::clear_has_name() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void CSCharacterCreate::clear_name() {
  if (name_ != &::google::protobuf::internal::kEmptyString) {
    name_->clear();
  }
  clear_has_name();
}
inline void CSCharacterCreate::name_to_mbs() {
*name_ = pwutils::utf8_to_mbs(*name_);
}
inline void CSCharacterCreate::name_to_utf8() {
*name_ = pwutils::utf8_from_mbs(*name_);
}
inline const ::std::string& CSCharacterCreate::name() const {
  return *name_;
}
inline void CSCharacterCreate::set_name(const ::std::string& value) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    name_ = new ::std::string;
  }
  name_->assign(value);
}
inline void CSCharacterCreate::set_name(const char* value) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    name_ = new ::std::string;
  }
  name_->assign(value);
}
inline void CSCharacterCreate::set_name(const void* value, size_t size) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    name_ = new ::std::string;
  }
  name_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* CSCharacterCreate::mutable_name() {
  set_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    name_ = new ::std::string;
  }
  return name_;
}
inline ::std::string* CSCharacterCreate::release_name() {
  clear_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = name_;
    name_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}

// required int32 profession = 2;
inline bool CSCharacterCreate::has_profession() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void CSCharacterCreate::set_has_profession() {
  _has_bits_[0] |= 0x00000002u;
}
inline void CSCharacterCreate::clear_has_profession() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void CSCharacterCreate::clear_profession() {
  profession_ = 0;
  clear_has_profession();
}
inline ::google::protobuf::int32 CSCharacterCreate::profession() const {
  return profession_;
}
inline void CSCharacterCreate::set_profession(::google::protobuf::int32 value) {
  set_has_profession();
  profession_ = value;
}

// required int32 sex = 3;
inline bool CSCharacterCreate::has_sex() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void CSCharacterCreate::set_has_sex() {
  _has_bits_[0] |= 0x00000004u;
}
inline void CSCharacterCreate::clear_has_sex() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void CSCharacterCreate::clear_sex() {
  sex_ = 0;
  clear_has_sex();
}
inline ::google::protobuf::int32 CSCharacterCreate::sex() const {
  return sex_;
}
inline void CSCharacterCreate::set_sex(::google::protobuf::int32 value) {
  set_has_sex();
  sex_ = value;
}

// -------------------------------------------------------------------

// SCCharacterCreate

// required int32 result = 1;
inline bool SCCharacterCreate::has_result() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void SCCharacterCreate::set_has_result() {
  _has_bits_[0] |= 0x00000001u;
}
inline void SCCharacterCreate::clear_has_result() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void SCCharacterCreate::clear_result() {
  result_ = 0;
  clear_has_result();
}
inline ::google::protobuf::int32 SCCharacterCreate::result() const {
  return result_;
}
inline void SCCharacterCreate::set_result(::google::protobuf::int32 value) {
  set_has_result();
  result_ = value;
}

// optional .pwngs.protocol.worldsrv.SCharacter character = 2;
inline bool SCCharacterCreate::has_character() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void SCCharacterCreate::set_has_character() {
  _has_bits_[0] |= 0x00000002u;
}
inline void SCCharacterCreate::clear_has_character() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void SCCharacterCreate::clear_character() {
  if (character_ != NULL) character_->::pwngs::protocol::worldsrv::SCharacter::Clear();
  clear_has_character();
}
inline const ::pwngs::protocol::worldsrv::SCharacter& SCCharacterCreate::character() const {
  return character_ != NULL ? *character_ : *default_instance_->character_;
}
inline ::pwngs::protocol::worldsrv::SCharacter* SCCharacterCreate::mutable_character() {
  set_has_character();
  if (character_ == NULL) character_ = new ::pwngs::protocol::worldsrv::SCharacter;
  return character_;
}
inline ::pwngs::protocol::worldsrv::SCharacter* SCCharacterCreate::release_character() {
  clear_has_character();
  ::pwngs::protocol::worldsrv::SCharacter* temp = character_;
  character_ = NULL;
  return temp;
}

// -------------------------------------------------------------------

// CSCharacterDelete

// required int64 id = 1;
inline bool CSCharacterDelete::has_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void CSCharacterDelete::set_has_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void CSCharacterDelete::clear_has_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void CSCharacterDelete::clear_id() {
  id_ = GOOGLE_LONGLONG(0);
  clear_has_id();
}
inline ::google::protobuf::int64 CSCharacterDelete::id() const {
  return id_;
}
inline void CSCharacterDelete::set_id(::google::protobuf::int64 value) {
  set_has_id();
  id_ = value;
}

// -------------------------------------------------------------------

// SCCharacterDelete

// required int32 result = 1;
inline bool SCCharacterDelete::has_result() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void SCCharacterDelete::set_has_result() {
  _has_bits_[0] |= 0x00000001u;
}
inline void SCCharacterDelete::clear_has_result() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void SCCharacterDelete::clear_result() {
  result_ = 0;
  clear_has_result();
}
inline ::google::protobuf::int32 SCCharacterDelete::result() const {
  return result_;
}
inline void SCCharacterDelete::set_result(::google::protobuf::int32 value) {
  set_has_result();
  result_ = value;
}

// optional int64 id = 2;
inline bool SCCharacterDelete::has_id() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void SCCharacterDelete::set_has_id() {
  _has_bits_[0] |= 0x00000002u;
}
inline void SCCharacterDelete::clear_has_id() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void SCCharacterDelete::clear_id() {
  id_ = GOOGLE_LONGLONG(0);
  clear_has_id();
}
inline ::google::protobuf::int64 SCCharacterDelete::id() const {
  return id_;
}
inline void SCCharacterDelete::set_id(::google::protobuf::int64 value) {
  set_has_id();
  id_ = value;
}

// optional int64 survive_time = 3;
inline bool SCCharacterDelete::has_survive_time() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void SCCharacterDelete::set_has_survive_time() {
  _has_bits_[0] |= 0x00000004u;
}
inline void SCCharacterDelete::clear_has_survive_time() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void SCCharacterDelete::clear_survive_time() {
  survive_time_ = GOOGLE_LONGLONG(0);
  clear_has_survive_time();
}
inline ::google::protobuf::int64 SCCharacterDelete::survive_time() const {
  return survive_time_;
}
inline void SCCharacterDelete::set_survive_time(::google::protobuf::int64 value) {
  set_has_survive_time();
  survive_time_ = value;
}

// -------------------------------------------------------------------

// SLadderInformation

// required int32 basemap = 1;
inline bool SLadderInformation::has_basemap() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void SLadderInformation::set_has_basemap() {
  _has_bits_[0] |= 0x00000001u;
}
inline void SLadderInformation::clear_has_basemap() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void SLadderInformation::clear_basemap() {
  basemap_ = 0;
  clear_has_basemap();
}
inline ::google::protobuf::int32 SLadderInformation::basemap() const {
  return basemap_;
}
inline void SLadderInformation::set_basemap(::google::protobuf::int32 value) {
  set_has_basemap();
  basemap_ = value;
}

// required int64 gamemap = 2;
inline bool SLadderInformation::has_gamemap() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void SLadderInformation::set_has_gamemap() {
  _has_bits_[0] |= 0x00000002u;
}
inline void SLadderInformation::clear_has_gamemap() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void SLadderInformation::clear_gamemap() {
  gamemap_ = GOOGLE_LONGLONG(0);
  clear_has_gamemap();
}
inline ::google::protobuf::int64 SLadderInformation::gamemap() const {
  return gamemap_;
}
inline void SLadderInformation::set_gamemap(::google::protobuf::int64 value) {
  set_has_gamemap();
  gamemap_ = value;
}

// -------------------------------------------------------------------

// CSCharacterLogin

// required int64 cid = 1;
inline bool CSCharacterLogin::has_cid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void CSCharacterLogin::set_has_cid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void CSCharacterLogin::clear_has_cid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void CSCharacterLogin::clear_cid() {
  cid_ = GOOGLE_LONGLONG(0);
  clear_has_cid();
}
inline ::google::protobuf::int64 CSCharacterLogin::cid() const {
  return cid_;
}
inline void CSCharacterLogin::set_cid(::google::protobuf::int64 value) {
  set_has_cid();
  cid_ = value;
}

// optional bytes mac = 2;
inline bool CSCharacterLogin::has_mac() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void CSCharacterLogin::set_has_mac() {
  _has_bits_[0] |= 0x00000002u;
}
inline void CSCharacterLogin::clear_has_mac() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void CSCharacterLogin::clear_mac() {
  if (mac_ != &::google::protobuf::internal::kEmptyString) {
    mac_->clear();
  }
  clear_has_mac();
}
inline void CSCharacterLogin::mac_to_mbs() {
*mac_ = pwutils::utf8_to_mbs(*mac_);
}
inline void CSCharacterLogin::mac_to_utf8() {
*mac_ = pwutils::utf8_from_mbs(*mac_);
}
inline const ::std::string& CSCharacterLogin::mac() const {
  return *mac_;
}
inline void CSCharacterLogin::set_mac(const ::std::string& value) {
  set_has_mac();
  if (mac_ == &::google::protobuf::internal::kEmptyString) {
    mac_ = new ::std::string;
  }
  mac_->assign(value);
}
inline void CSCharacterLogin::set_mac(const char* value) {
  set_has_mac();
  if (mac_ == &::google::protobuf::internal::kEmptyString) {
    mac_ = new ::std::string;
  }
  mac_->assign(value);
}
inline void CSCharacterLogin::set_mac(const void* value, size_t size) {
  set_has_mac();
  if (mac_ == &::google::protobuf::internal::kEmptyString) {
    mac_ = new ::std::string;
  }
  mac_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* CSCharacterLogin::mutable_mac() {
  set_has_mac();
  if (mac_ == &::google::protobuf::internal::kEmptyString) {
    mac_ = new ::std::string;
  }
  return mac_;
}
inline ::std::string* CSCharacterLogin::release_mac() {
  clear_has_mac();
  if (mac_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = mac_;
    mac_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}

// optional .pwngs.protocol.worldsrv.SLadderInformation ladder_info = 3;
inline bool CSCharacterLogin::has_ladder_info() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void CSCharacterLogin::set_has_ladder_info() {
  _has_bits_[0] |= 0x00000004u;
}
inline void CSCharacterLogin::clear_has_ladder_info() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void CSCharacterLogin::clear_ladder_info() {
  if (ladder_info_ != NULL) ladder_info_->::pwngs::protocol::worldsrv::SLadderInformation::Clear();
  clear_has_ladder_info();
}
inline const ::pwngs::protocol::worldsrv::SLadderInformation& CSCharacterLogin::ladder_info() const {
  return ladder_info_ != NULL ? *ladder_info_ : *default_instance_->ladder_info_;
}
inline ::pwngs::protocol::worldsrv::SLadderInformation* CSCharacterLogin::mutable_ladder_info() {
  set_has_ladder_info();
  if (ladder_info_ == NULL) ladder_info_ = new ::pwngs::protocol::worldsrv::SLadderInformation;
  return ladder_info_;
}
inline ::pwngs::protocol::worldsrv::SLadderInformation* CSCharacterLogin::release_ladder_info() {
  clear_has_ladder_info();
  ::pwngs::protocol::worldsrv::SLadderInformation* temp = ladder_info_;
  ladder_info_ = NULL;
  return temp;
}

// -------------------------------------------------------------------

// SServerInformation

// required int64 zone_id = 1;
inline bool SServerInformation::has_zone_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void SServerInformation::set_has_zone_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void SServerInformation::clear_has_zone_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void SServerInformation::clear_zone_id() {
  zone_id_ = GOOGLE_LONGLONG(0);
  clear_has_zone_id();
}
inline ::google::protobuf::int64 SServerInformation::zone_id() const {
  return zone_id_;
}
inline void SServerInformation::set_zone_id(::google::protobuf::int64 value) {
  set_has_zone_id();
  zone_id_ = value;
}

// required bytes operators_name = 2;
inline bool SServerInformation::has_operators_name() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void SServerInformation::set_has_operators_name() {
  _has_bits_[0] |= 0x00000002u;
}
inline void SServerInformation::clear_has_operators_name() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void SServerInformation::clear_operators_name() {
  if (operators_name_ != &::google::protobuf::internal::kEmptyString) {
    operators_name_->clear();
  }
  clear_has_operators_name();
}
inline void SServerInformation::operators_name_to_mbs() {
*operators_name_ = pwutils::utf8_to_mbs(*operators_name_);
}
inline void SServerInformation::operators_name_to_utf8() {
*operators_name_ = pwutils::utf8_from_mbs(*operators_name_);
}
inline const ::std::string& SServerInformation::operators_name() const {
  return *operators_name_;
}
inline void SServerInformation::set_operators_name(const ::std::string& value) {
  set_has_operators_name();
  if (operators_name_ == &::google::protobuf::internal::kEmptyString) {
    operators_name_ = new ::std::string;
  }
  operators_name_->assign(value);
}
inline void SServerInformation::set_operators_name(const char* value) {
  set_has_operators_name();
  if (operators_name_ == &::google::protobuf::internal::kEmptyString) {
    operators_name_ = new ::std::string;
  }
  operators_name_->assign(value);
}
inline void SServerInformation::set_operators_name(const void* value, size_t size) {
  set_has_operators_name();
  if (operators_name_ == &::google::protobuf::internal::kEmptyString) {
    operators_name_ = new ::std::string;
  }
  operators_name_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* SServerInformation::mutable_operators_name() {
  set_has_operators_name();
  if (operators_name_ == &::google::protobuf::internal::kEmptyString) {
    operators_name_ = new ::std::string;
  }
  return operators_name_;
}
inline ::std::string* SServerInformation::release_operators_name() {
  clear_has_operators_name();
  if (operators_name_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = operators_name_;
    operators_name_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}

// -------------------------------------------------------------------

// SCCharacterLogin

// required int32 result = 1;
inline bool SCCharacterLogin::has_result() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void SCCharacterLogin::set_has_result() {
  _has_bits_[0] |= 0x00000001u;
}
inline void SCCharacterLogin::clear_has_result() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void SCCharacterLogin::clear_result() {
  result_ = 0;
  clear_has_result();
}
inline ::google::protobuf::int32 SCCharacterLogin::result() const {
  return result_;
}
inline void SCCharacterLogin::set_result(::google::protobuf::int32 value) {
  set_has_result();
  result_ = value;
}

// optional bytes error = 2;
inline bool SCCharacterLogin::has_error() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void SCCharacterLogin::set_has_error() {
  _has_bits_[0] |= 0x00000002u;
}
inline void SCCharacterLogin::clear_has_error() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void SCCharacterLogin::clear_error() {
  if (error_ != &::google::protobuf::internal::kEmptyString) {
    error_->clear();
  }
  clear_has_error();
}
inline void SCCharacterLogin::error_to_mbs() {
*error_ = pwutils::utf8_to_mbs(*error_);
}
inline void SCCharacterLogin::error_to_utf8() {
*error_ = pwutils::utf8_from_mbs(*error_);
}
inline const ::std::string& SCCharacterLogin::error() const {
  return *error_;
}
inline void SCCharacterLogin::set_error(const ::std::string& value) {
  set_has_error();
  if (error_ == &::google::protobuf::internal::kEmptyString) {
    error_ = new ::std::string;
  }
  error_->assign(value);
}
inline void SCCharacterLogin::set_error(const char* value) {
  set_has_error();
  if (error_ == &::google::protobuf::internal::kEmptyString) {
    error_ = new ::std::string;
  }
  error_->assign(value);
}
inline void SCCharacterLogin::set_error(const void* value, size_t size) {
  set_has_error();
  if (error_ == &::google::protobuf::internal::kEmptyString) {
    error_ = new ::std::string;
  }
  error_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* SCCharacterLogin::mutable_error() {
  set_has_error();
  if (error_ == &::google::protobuf::internal::kEmptyString) {
    error_ = new ::std::string;
  }
  return error_;
}
inline ::std::string* SCCharacterLogin::release_error() {
  clear_has_error();
  if (error_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = error_;
    error_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}

// -------------------------------------------------------------------

// CSCharacterEnterWorld

// required int64 id = 1;
inline bool CSCharacterEnterWorld::has_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void CSCharacterEnterWorld::set_has_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void CSCharacterEnterWorld::clear_has_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void CSCharacterEnterWorld::clear_id() {
  id_ = GOOGLE_LONGLONG(0);
  clear_has_id();
}
inline ::google::protobuf::int64 CSCharacterEnterWorld::id() const {
  return id_;
}
inline void CSCharacterEnterWorld::set_id(::google::protobuf::int64 value) {
  set_has_id();
  id_ = value;
}

// -------------------------------------------------------------------

// CSCharacterRevert

// required int64 id = 1;
inline bool CSCharacterRevert::has_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void CSCharacterRevert::set_has_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void CSCharacterRevert::clear_has_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void CSCharacterRevert::clear_id() {
  id_ = GOOGLE_LONGLONG(0);
  clear_has_id();
}
inline ::google::protobuf::int64 CSCharacterRevert::id() const {
  return id_;
}
inline void CSCharacterRevert::set_id(::google::protobuf::int64 value) {
  set_has_id();
  id_ = value;
}

// -------------------------------------------------------------------

// SCCharacterRevert

// required int32 result = 1;
inline bool SCCharacterRevert::has_result() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void SCCharacterRevert::set_has_result() {
  _has_bits_[0] |= 0x00000001u;
}
inline void SCCharacterRevert::clear_has_result() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void SCCharacterRevert::clear_result() {
  result_ = 0;
  clear_has_result();
}
inline ::google::protobuf::int32 SCCharacterRevert::result() const {
  return result_;
}
inline void SCCharacterRevert::set_result(::google::protobuf::int32 value) {
  set_has_result();
  result_ = value;
}

// optional int64 id = 2;
inline bool SCCharacterRevert::has_id() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void SCCharacterRevert::set_has_id() {
  _has_bits_[0] |= 0x00000002u;
}
inline void SCCharacterRevert::clear_has_id() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void SCCharacterRevert::clear_id() {
  id_ = GOOGLE_LONGLONG(0);
  clear_has_id();
}
inline ::google::protobuf::int64 SCCharacterRevert::id() const {
  return id_;
}
inline void SCCharacterRevert::set_id(::google::protobuf::int64 value) {
  set_has_id();
  id_ = value;
}

// -------------------------------------------------------------------

// SCDroppedHumanHint

// required int64 dropped_hid = 1;
inline bool SCDroppedHumanHint::has_dropped_hid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void SCDroppedHumanHint::set_has_dropped_hid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void SCDroppedHumanHint::clear_has_dropped_hid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void SCDroppedHumanHint::clear_dropped_hid() {
  dropped_hid_ = GOOGLE_LONGLONG(0);
  clear_has_dropped_hid();
}
inline ::google::protobuf::int64 SCDroppedHumanHint::dropped_hid() const {
  return dropped_hid_;
}
inline void SCDroppedHumanHint::set_dropped_hid(::google::protobuf::int64 value) {
  set_has_dropped_hid();
  dropped_hid_ = value;
}

// required int32 dropped_scene = 2;
inline bool SCDroppedHumanHint::has_dropped_scene() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void SCDroppedHumanHint::set_has_dropped_scene() {
  _has_bits_[0] |= 0x00000002u;
}
inline void SCDroppedHumanHint::clear_has_dropped_scene() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void SCDroppedHumanHint::clear_dropped_scene() {
  dropped_scene_ = 0;
  clear_has_dropped_scene();
}
inline ::google::protobuf::int32 SCDroppedHumanHint::dropped_scene() const {
  return dropped_scene_;
}
inline void SCDroppedHumanHint::set_dropped_scene(::google::protobuf::int32 value) {
  set_has_dropped_scene();
  dropped_scene_ = value;
}

// required int64 request_hid = 3;
inline bool SCDroppedHumanHint::has_request_hid() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void SCDroppedHumanHint::set_has_request_hid() {
  _has_bits_[0] |= 0x00000004u;
}
inline void SCDroppedHumanHint::clear_has_request_hid() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void SCDroppedHumanHint::clear_request_hid() {
  request_hid_ = GOOGLE_LONGLONG(0);
  clear_has_request_hid();
}
inline ::google::protobuf::int64 SCDroppedHumanHint::request_hid() const {
  return request_hid_;
}
inline void SCDroppedHumanHint::set_request_hid(::google::protobuf::int64 value) {
  set_has_request_hid();
  request_hid_ = value;
}

// -------------------------------------------------------------------

// CSKickDroppedHuman

// -------------------------------------------------------------------

// CSLoginEnded


// @@protoc_insertion_point(namespace_scope)

}  // namespace worldsrv
}  // namespace protocol
}  // namespace pwngs

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_process_5fproto_2f01000_5f01009_5flogin_2eproto__INCLUDED
