//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by MagicEditor.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_MAGICEDITOR_DIALOG          102
#define IDR_MAINFRAME                   128
#define IDD_DIALOG_MAGICTYPE            129
#define IDD_DIALOG_EFFECTCOMMON         130
#define IDD_DIALOG_MAGICTYPE_HUMAN      131
#define IDD_DIALOG_MAGICTYPE_NPC        132
#define IDD_DIALOG_AURA                 133
#define IDD_DIALOG_AURAEFFECT           134
#define IDD_DIALOG_EFFECTCOLLISION      135
#define IDD_DIALOG_EFFECTMOTION         136
#define IDD_DIALOG_EFFECTFLEXIBLE       137
#define IDC_MAIN_TREE                   1000
#define IDC_MAIN_LOG                    1001
#define IDC_MAIN_TAB                    1002
#define IDC_MAGIC_ID                    1003
#define IDC_EFFECTCOMMON_commonID       1003
#define IDC_MAGIC_magicName             1004
#define IDC_MAGIC_dodgeDis              1004
#define IDC_EFFECTCOMMON_delay          1004
#define IDC_MAGIC_dodgeTime             1005
#define IDC_EFFECTCOMMON_objectNum      1005
#define IDC_AURA_desc                   1005
#define IDC_AURAEFFECT_cycleTime        1005
#define IDC_MAGIC_keyHold               1006
#define IDC_EFFECTCOMMON_beatenPerformanceID 1006
#define IDC_AURA_iconGroup              1006
#define IDC_AURAEFFECT_triggerCondition 1006
#define IDC_MAGIC_isContinusMagic       1007
#define IDC_EFFECTCOMMON_deadSmashProbablity 1007
#define IDC_AURA_icon                   1007
#define IDC_AURAEFFECT_internalCD       1007
#define IDC_MAGIC_allowInterruptDelay   1008
#define IDC_MAGIC_ContinusMagic         1008
#define IDC_EFFECTCOMMON_beatBackDistMin 1008
#define IDC_AURAEFFECT_trigger_id       1008
#define IDC_EFFECTCOMMON_beatBackProbablity 1009
#define IDC_EFFECTFLEXIBLE_charm_type   1009
#define IDC_AURA_groupDes               1009
#define IDC_EFFECTCOMMON_beatBackDistMax 1010
#define IDC_EFFECTFLEXIBLE_performance  1010
#define IDC_AURA_groupPriority          1010
#define IDC_MAGIC_attackLimit           1011
#define IDC_EFFECTCOMMON_beatEnergyInc  1011
#define IDC_EFFECTMOTION_bginSkillID    1011
#define IDC_AURA_defaultLayers          1011
#define IDC_MAGIC_CDTime                1012
#define IDC_MAGIC_moveLimit             1012
#define IDC_EFFECTCOMMON_beatEnergyIncPara 1012
#define IDC_EFFECTMOTION_skillID        1012
#define IDC_AURA_maxLayers              1012
#define IDC_MAGIC_CDGroup               1013
#define IDC_MAGIC_lockTarget            1013
#define IDC_EFFECTCOMMON_des            1013
#define IDC_EFFECTMOTION_delay          1013
#define IDC_AURA_auraTime               1013
#define IDC_MAGIC_CDGroupTime           1014
#define IDC_AURA_auraRadius             1014
#define IDC_EFFECTCOMMON_physicsForce   1014
#define IDC_EFFECTMOTION_bginSkillDes   1014
#define IDC_MAGIC_maxCastDistance       1015
#define IDC_AURA_auraUpdateTime         1015
#define IDC_EFFECTCOMMON_physicsForceAdjustAngle 1015
#define IDC_EFFECTMOTION_skillDes       1015
#define IDC_MAGIC_dodgeType             1016
#define IDC_EFFECTCOLLISION_maxCollisionTimes 1016
#define IDC_AURA_ClientEffect           1016
#define IDC_EFFECTCOMMON_physicsForceAdjustY 1016
#define IDC_MAGIC_castTarget            1017
#define IDC_MAGIC_is_add_mp_dodge       1017
#define IDC_EFFECTCOLLISION_flyPerformanceID 1017
#define IDC_AURA_validStages            1017
#define IDC_MAGIC_magicType             1018
#define IDC_MAGIC_SkillLevel            1018
#define IDC_EFFECTCOLLISION_bind        1018
#define IDC_EFFECTCOMMON_hitBuffChance1 1018
#define IDC_AURA_groupOper              1018
#define IDC_MAGIC_add_mp_use_magic      1019
#define IDC_MAGIC_magicBelong           1019
#define IDC_EFFECTCOLLISION_charPerformanceID 1019
#define IDC_EFFECTCOMMON_hitBuff1       1019
#define IDC_AURA_groupID                1019
#define IDC_MAGIC_add_mp_hit_first      1020
#define IDC_EFFECTCOLLISION_scale       1020
#define IDC_EFFECTCOMMON_hitBuffDes1    1020
#define IDC_AURA_ClientEffectDes        1020
#define IDC_MAGIC_add_mp_hit_other      1021
#define IDC_EFFECTCOLLISION_delay       1021
#define IDC_AURA_liveStyle              1021
#define IDC_EFFECTCOMMON_hitBuffChance2 1021
#define IDC_MAGIC_castBackswingTime     1022
#define IDC_MAGIC_upgradeField          1022
#define IDC_AURA_EffectTarget           1022
#define IDC_EFFECTCOMMON_hitBuff2       1022
#define IDC_EFFECTCOLLISION_aura        1022
#define IDC_MAGIC_autoSkillPriority     1023
#define IDC_AURA_type                   1023
#define IDC_EFFECTCOMMON_hitBuffDes2    1023
#define IDC_MAGIC_autoSkillType         1024
#define IDC_EFFECTCOMMON_hitBuffChance3 1024
#define IDC_MAGIC_isActive              1025
#define IDC_MAGIC_levelRange            1025
#define IDC_EFFECTCOMMON_hitBuff3       1025
#define IDC_MAGIC_interruptWhenHurt     1026
#define IDC_MAGIC_nextID                1026
#define IDC_AURA_managerByMagic         1026
#define IDC_EFFECTCOMMON_hitBuffDes3    1026
#define IDC_MAGIC_isPublicCD            1027
#define IDC_MAGIC_lockTargetDie         1027
#define IDC_AURA_isendSceneSwitch       1027
#define IDC_EFFECTCOMMON_physics_if_top 1027
#define IDC_MAGIC_effectTarget          1028
#define IDC_MAGIC_default_loc           1028
#define IDC_AURA_isendDeath             1028
#define IDC_EFFECTCOMMON_physics_if_middle 1028
#define IDC_MAGIC_clientCastSwingTime   1029
#define IDC_MAGIC_enable_loc            1029
#define IDC_AURA_isendOffline           1029
#define IDC_EFFECTCOMMON_physics_if_bottom 1029
#define IDC_MAGIC_castSwingTime         1030
#define IDC_AURA_isOfflineTiming        1030
#define IDC_EFFECTCOMMON_isMustHit      1030
#define IDC_MAGIC_castStiffTime         1031
#define IDC_AURA_flags                  1031
#define IDC_EFFECTCOMMON_hurtPercentagePhys 1031
#define IDC_MAGIC_magicPerformanceID    1032
#define IDC_AURA_auraTarget             1032
#define IDC_EFFECTCOMMON_hurtValuePhys  1032
#define IDC_MAGIC_magicAttackType       1033
#define IDC_EFFECTCOMMON_hurtValueMaxPhys 1033
#define IDC_MAGIC_imageSet              1034
#define IDC_MAGIC_profession            1034
#define IDC_EFFECTCOMMON_hurtPercentagePhysMods 1034
#define IDC_MAGIC_magicIconID           1035
#define IDC_MAGIC_stopMove              1035
#define IDC_EFFECTCOMMON_hurtValuePhysMods 1035
#define IDC_EFFECTCOLLISION_hitOnce     1036
#define IDC_EFFECTCOMMON_hurtValueMaxPhysMods 1036
#define IDC_MAGIC_consumeValue          1036
#define IDC_MAGIC_magicPerformanceDes   1036
#define IDC_MAGIC_SUB_magicBelong       1037
#define IDC_EFFECTCOMMON_hurtPercentageMage 1037
#define IDC_EFFECTCOLLISION_hitOnce2    1037
#define IDC_EFFECTCOLLISION_hitOnceG    1037
#define IDC_MAGIC_EFFECTS               1038
#define IDC_EFFECTCOMMON_hurtValueMage  1038
#define IDC_BUTTON1                     1039
#define IDC_EFFECTCOMMON_hurtValueMaxMage 1039
#define IDC_BUTTON2                     1040
#define IDC_EFFECTCOMMON_hurtPercentageMageMods 1040
#define IDC_MAGIC_additionEffect        1041
#define IDC_EFFECTCOMMON_hurtValueMageMods 1041
#define IDC_MAGIC_additionEffectParam1  1042
#define IDC_EFFECTCOMMON_hurtValueMaxMageMods 1042
#define IDC_MAGIC_additionEffectParam2  1043
#define IDC_EFFECTCOMMON_additionalFireHurtValue 1043
#define IDC_MAGIC_additionEffectParam3  1044
#define IDC_EFFECTCOMMON_additionalColdHurtValue 1044
#define IDC_MAGIC_additionEffectParam4  1045
#define IDC_EFFECTCOMMON_additionalFireHurtValueMods 1045
#define IDC_MAGIC_additionEffectParam5  1046
#define IDC_EFFECTCOMMON_additionalColdHurtValueMods 1046
#define IDC_MAGIC_additionEffectParam6  1047
#define IDC_EFFECTCOMMON_additionalLightHurtValue 1047
#define IDC_AURAEFFECT_paraDes1         1048
#define IDC_EFFECTCOMMON_additionalPoisonHurtValue 1048
#define IDC_MAGIC_targetPerformanceID   1048
#define IDC_AURAEFFECT_paraDes2         1049
#define IDC_EFFECTCOMMON_additionalLightHurtValueMods 1049
#define IDC_MAGIC_targetPerformanceDes  1049
#define IDC_AURAEFFECT_paraDes3         1050
#define IDC_EFFECTCOMMON_additionalPoisonHurtValueMods 1050
#define IDC_MAGIC_showSwing             1050
#define IDC_AURAEFFECT_paraDes4         1051
#define IDC_EFFECTCOMMON_additionalFireHurtTransRate 1051
#define IDC_MAGIC_castTargetCondition   1051
#define IDC_AURAEFFECT_paraDes5         1052
#define IDC_EFFECTCOMMON_additionalColdHurtTransRate 1052
#define IDC_AURAEFFECT_paraDes6         1053
#define IDC_EFFECTCOMMON_additionalLightHurtTransRate 1053
#define IDC_EDIT_FIND                   1054
#define IDC_AURAEFFECT_paraDes1_lvmod   1054
#define IDC_EFFECTCOMMON_additionalPoisonHurtTransRate 1054
#define IDC_EDIT_TOTAL                  1055
#define IDC_AURAEFFECT_para1_lvmod      1055
#define IDC_EFFECTCOMMON_additionalFireHurtTransRateMods 1055
#define IDC_BUTTON_FIND                 1056
#define IDC_AURAEFFECT_para2_lvmod      1056
#define IDC_EFFECTCOMMON_additionalColdHurtTransRateMods 1056
#define IDC_AURAEFFECT_para3_lvmod      1057
#define IDC_EFFECTCOMMON_additionalLightHurtTransRateMods 1057
#define IDC_EFFECTCOMMON_effectBits     1058
#define IDC_AURAEFFECT_para4_lvmod      1058
#define IDC_EFFECTCOMMON_rangeType      1059
#define IDC_AURAEFFECT_para5_lvmod      1059
#define IDC_EFFECTCOMMON_rangePara1     1060
#define IDC_AURAEFFECT_para6_lvmod      1060
#define IDC_EFFECTCOMMON_rangeDes1      1061
#define IDC_EFFECTFLEXIBLE_ffparam2     1061
#define IDC_AURAEFFECT_paraDes2_lvmod   1061
#define IDC_EFFECTCOMMON_rangeDes2      1062
#define IDC_EFFECTFLEXIBLE_ffparam3     1062
#define IDC_AURAEFFECT_paraDes3_lvmod   1062
#define IDC_EFFECTCOMMON_rangeDes3      1063
#define IDC_AURAEFFECT_paraDes4_lvmod   1063
#define IDC_EFFECTCOMMON_rangePara2     1064
#define IDC_AURAEFFECT_paraDes5_lvmod   1064
#define IDC_EFFECTCOMMON_rangePara3     1065
#define IDC_AURAEFFECT_paraDes6_lvmod   1065
#define IDC_EFFECTCOMMON_rangePara4     1066
#define IDC_EFFECTFLEXIBLE_nnparamDes3  1066
#define IDC_EFFECTCOMMON_rangeDes4      1067
#define IDC_EFFECTFLEXIBLE_ffparamDes1  1067
#define IDC_EFFECTCOMMON_beatBackType   1068
#define IDC_EFFECTFLEXIBLE_ffparamDes2  1068
#define IDC_EFFECTCOLLISION_collisionID 1069
#define IDC_EFFECTFLEXIBLE_ffparamDes3  1069
#define IDC_EFFECTMOTION_timeControl    1069
#define IDC_EFFECTCOMMON_physicsForceType 1069
#define IDC_EFFECTCOLLISION_des         1070
#define IDC_EFFECTFLEXIBLE_objParamDes1 1070
#define IDC_EFFECTMOTION_barrier_type   1070
#define IDC_EFFECTCOMMON_additionalHurtType 1070
#define IDC_EFFECTCOLLISION_objType     1071
#define IDC_EFFECTFLEXIBLE_objParamDes2 1071
#define IDC_EFFECTMOTION_skillTarget    1071
#define IDC_EFFECTCOMMON_additionalHurtTransType 1071
#define IDC_EFFECTCOLLISION_objParamDes1 1072
#define IDC_EFFECTFLEXIBLE_objParamDes3 1072
#define IDC_EFFECTMOTION_movetype       1072
#define IDC_EFFECTCOMMON_physicsForceHeight 1072
#define IDC_EFFECTCOLLISION_objParam1   1073
#define IDC_EFFECTCOMMON_additionalPoisonHurtTransRateMods 1073
#define IDC_EFFECTCOLLISION_objParamDes2 1074
#define IDC_EFFECTCOMMON_humanAttrHurtTransRate 1074
#define IDC_EFFECTCOLLISION_objParam2   1075
#define IDC_EFFECTCOLLISION_objParamDes3 1076
#define IDC_EFFECTCOLLISION_objParam3   1077
#define IDC_EFFECTCOLLISION_generateType 1078
#define IDC_EFFECTCOLLISION_generateNum 1079
#define IDC_EFFECTCOLLISION_bulletGap   1080
#define IDC_EFFECTCOLLISION_bezierId    1081
#define IDC_EFFECTCOLLISION_maxDist     1082
#define IDC_EFFECTCOLLISION_speed       1083
#define IDC_EFFECTCOLLISION_skillID     1084
#define IDC_EFFECTCOLLISION_skillDes    1085
#define IDC_EFFECTCOLLISION_hasFinalEffect 1086
#define IDC_EFFECTFLEXIBLE_ID           1087
#define IDC_EFFECTCOLLISION_flyPerformanceDes 1087
#define IDC_EFFECTFLEXIBLE_des          1088
#define IDC_EFFECTCOLLISION_flyPerformanceDes2 1088
#define IDC_EFFECTCOLLISION_auraDes     1088
#define IDC_EFFECTFLEXIBLE_objType      1089
#define IDC_EFFECTFLEXIBLE_objParam1    1090
#define IDC_EFFECTFLEXIBLE_objParam2    1091
#define IDC_EFFECTFLEXIBLE_objParam3    1092
#define IDC_EFFECTFLEXIBLE_type         1093
#define IDC_EFFECTFLEXIBLE_nparam1      1094
#define IDC_EFFECTFLEXIBLE_nparamDes1   1095
#define IDC_EFFECTFLEXIBLE_fparamDes1   1096
#define IDC_EFFECTFLEXIBLE_nnparamDes1  1097
#define IDC_EFFECTFLEXIBLE_fparam1      1098
#define IDC_EFFECTFLEXIBLE_nnparam1     1099
#define IDC_EFFECTFLEXIBLE_ffparam1     1100
#define IDC_EFFECTFLEXIBLE_nparamDes2   1101
#define IDC_EFFECTFLEXIBLE_fparamDes2   1102
#define IDC_EFFECTFLEXIBLE_nnparamDes2  1103
#define IDC_EFFECTFLEXIBLE_nparam2      1104
#define IDC_EFFECTFLEXIBLE_fparam2      1105
#define IDC_EFFECTFLEXIBLE_nnparam2     1106
#define IDC_EFFECTFLEXIBLE_nparamDes3   1107
#define IDC_EFFECTFLEXIBLE_fparamDes3   1108
#define IDC_EFFECTFLEXIBLE_nparam3      1109
#define IDC_EFFECTFLEXIBLE_fparam3      1110
#define IDC_EFFECTFLEXIBLE_nnparam3     1111
#define IDC_EFFECTFLEXIBLE_delay        1112
#define IDC_MAGIC_additionEffectDes1    1113
#define IDC_MAGIC_additionEffectDes4    1114
#define IDC_MAGIC_additionEffectDes2    1115
#define IDC_MAGIC_additionEffectDes5    1116
#define IDC_MAGIC_additionEffectDes3    1117
#define IDC_MAGIC_additionEffectDes6    1118
#define IDC_EFFECTMOTION_motionID       1119
#define IDC_EFFECTMOTION_des            1120
#define IDC_EFFECTMOTION_objType        1121
#define IDC_EFFECTMOTION_objParamDes1   1122
#define IDC_EFFECTMOTION_objParam1      1123
#define IDC_EFFECTMOTION_objParamDes2   1124
#define IDC_EFFECTMOTION_objParam2      1125
#define IDC_EFFECTMOTION_objParamDes3   1126
#define IDC_EFFECTMOTION_objParam3      1127
#define IDC_EFFECTMOTION_motionPattern  1128
#define IDC_EFFECTMOTION_motionPerformancePattern 1129
#define IDC_EFFECTMOTION_moveTime       1130
#define IDC_AURA_ID                     1131
#define IDC_AURA_name                   1132
#define IDC_AURA_friendlyLevel          1133
#define IDC_AURA_isIconDisplay          1134
#define IDC_AURA_EFFECTS                1135
#define IDC_AURAEFFECT_ID               1136
#define IDC_AURAEFFECT_desc             1137
#define IDC_AURAEFFECT_type             1138
#define IDC_AURAEFFECT_para1            1139
#define IDC_AURAEFFECT_para2            1140
#define IDC_AURAEFFECT_para3            1141
#define IDC_AURAEFFECT_para4            1142
#define IDC_AURAEFFECT_para5            1143
#define IDC_AURAEFFECT_para6            1144
#define IDC_EFFECTFLEXIBLE_typeDes      1145
#define IDC_AURAEFFECT_para1Tips        1145
#define IDC_EFFECTFLEXIBLE_charm_typeDes 1147
#define IDC_EFFECTFLEXIBLE_performanceDes 1148
#define IDC_MAGIC_additionEffectDes     1149
#define IDC_AURAEFFECT_typeDes          1150
#define IDC_AURAEFFECT_cycleTimeDes     1151
#define IDC_EFFECTCOLLISION_flags       1152

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        138
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1153
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
