#ifndef _pw_ngs_qlvh_def_
#define _pw_ngs_qlvh_def_

namespace pwngs
{
	enum
	{
		WMLOG_MASK0_LOGIN = (1 << 0),
		WMLOG_MASK0_LOGOUT = (1 << 1),
		WMLOG_MASK0_ONLINEUSER = (1 << 2),
		WMLOG_MASK0_ADDCASH = (1 << 3),
		WMLOG_MASK0_UPGRADE = (1 << 4),
		WMLOG_MASK0_MONEY = (1 << 5),
		WMLOG_MASK0_QUEST = (1 << 6),
		WMLOG_MASK0_CREATEROLE = (1 << 7),
		WMLOG_MASK0_CHANGEROLE = (1 << 8),
		WMLOG_MASK0_NEWUSER = (1 << 9),
		WMLOG_MASK0_DICTITEM = (1 << 10),
		WMLOG_MASK0_OPENPLAYENTRY = (1 << 11),
		WMLOG_MASK0_DRAGONSTATUS = (1 << 12),
		WMLOG_MASK0_GEM = (1 << 13),
		WMLOG_MASK0_BEHAVIOR = (1 << 14),
		WMLOG_MASK0_ARENA = (1 << 15),
		WMLOG_MASK0_BATTLE = (1 << 16),
		WMLOG_MASK0_DUNGEON = (1 << 17),
		WMLOG_MASK0_ITEM = (1 << 18),
		WMLOG_MASK0_CREATEROLE_LOSS = (1 << 19),
		WMLOG_MASK0_ACTIVITY_PCU = (1 << 20),
		WMLOG_MASK0_BLOODFUSION = (1 << 21),
		WMLOG_MASK0_PLAY = (1 << 22),
		WMLOG_MASK0_SNAPSHOT_SKILL = (1 << 23),
		WMLOG_MASK0_SNAPSHOT_EQUIP = (1 << 24),
		WMLOG_MASK0_SNAPSHOT_CASH = (1 << 25),
		WMLOG_MASK0_SNAPSHOT_BABEL = (1 << 26),
		WMLOG_MASK0_SNAPSHOT_VIPUPGRADE = (1 << 27),
		WMLOG_MASK0_COMMON_ACTIVITY_REWARD = (1 << 28),
		WMLOG_MASK0_CHARGE_CALLBACK_REWARD = (1 << 29),
		WMLOG_MASK0_DAILY_RECHARGE_AWARD = (1 << 30),
		WMLOG_MASK0_SNAPSHOT_COMMON = (1 << 31),
		WMLOG_MASK0_SNAPSHOT_EQUIPMENT_DATA = (1 << 32),
	};
}

#endif // _pw_ngs_qlvh_def_