#ifndef _pw_public_data_def_
#define _pw_public_data_def_

namespace pwngs
{
	enum EPublicConstType
	{
		PUBLIC_CONST_TYPE_NONE = 0,

		PUBLIC_CONST_TYPE_HERO_SUMMON_GCD		= 1,	// 英雄公共CD
		PUBLIC_CONST_TYPE_HERO_SUMMON_BUF		= 2,	// 英雄召唤BUFF
		PUBLIC_CONST_TYPE_CHAT_CD				= 3,	// 聊天CD
		PUBLIC_CONST_TYPE_CHAT_LEVEL			= 4,	// 聊天等级
		PUBLIC_CONST_TYPE_HORN_LEVEL			= 5,	// 喇叭等级
		PUBLIC_CONST_TYPE_HORN_SPEND			= 6,	// 喇叭消耗
		PUBLIC_CONST_TYPE_CREATE_GUILD_LV,		// 创建帮会等级
		PUBLIC_CONST_TYPE_APPLY_GUILD_LV,		// 申请帮会等级
		PUBLIC_CONST_TYPE_DISMISS_GUILD_CNT,	// 帮派解散最小人数
		PUBLIC_CONST_TYPE_DISMISS_GUILD_HOUR,	// 帮派解散最少时间，小时
		PUBLIC_CONST_TYPE_APPLY_GUILD_MAX,		// 最多申请帮派数
		PUBLIC_CONST_TYPE_APPLY_GUILD_LIST_MAX, // 帮派申请列表最多人数
		PUBLIC_CONST_TYPE_GUILD_RECRUIT_CD,		// 帮派招募CD，单位秒
		PUBLIC_CONST_TYPE_GUILD_LOG_MAX,		// 帮派日志保存最多条数
		PUBLIC_CONST_TYPE_GUILD_OFFLINE,		// 帮主弹劾离线天数
		PUBLIC_CONST_TYPE_GUILD_CONTRI_SAVE,	// 脱离帮派贡献保留百分比
		PUBLIC_CONST_TYPE_MAIL_DAYS,			// 邮件保留天数
		PUBLIC_CONST_TYPE_MAIL_COUNT,			// 邮件保留数量
		PUBLIC_CONST_TYPE_GUILD_CREATE_YB,		// 创建帮派元宝数
		PUBLIC_CONST_TYPE_GUILD_CREATE_COIN,	// 创建帮派铜钱数
		PUBLIC_CONST_TYPE_GUILD_DENOTE_MAX,		// 帮派捐献每日可捐献次数
		PUBLIC_CONST_TYPE_GUILD_NOTICE_CD,		// 帮派公告编辑CD，单位秒

		PUBLIC_CONST_TYPE_ADD_FRIEND_LV			=27,	 //添加好友等级限制

		PUBLIC_CONST_TYPE_WARLORD_NPC_BASE_ID	= 30,	//华山论剑怪物起始ID
		PUBLIC_CONST_TYPE_WARLORD_NPC_COUNT		= 31,	//华山论剑怪物数量
		PUBLIC_CONST_TYPE_WARLORD_CD_SEC		= 32,	//挑战CD
		PUBLIC_CONST_TYPE_WARLORD_COST_GOLD		= 33,	//华山论剑挑战CD购买消耗元宝
		PUBLIC_CONST_TYPE_WARLOAD_SHOP_LV		= 34,   //华山论剑商店开放等级
		PUBLIC_CONST_TYPE_DTS_1FLOOR_ITEMS		= 35,   //迷宫第一层道具上限数量
		PUBLIC_CONST_TYPE_DTS_2FLOOR_ITEMS		= 36,	//迷宫可传送第二层道具数量
		PUBLIC_CONST_TYPE_PVE_STAGE_ID			= 37,	//PVE襄阳守卫场景Id
		PUBLIC_CONST_TYPE_PVE_MIN_MEMBER		= 38,	//PVE襄阳守卫开始最少人数
		PUBLIC_CONST_TYPE_NJTZ_START_WEEK		= 39,	//帮派战筛选（周几）
		PUBLIC_CONST_TYPE_NJTZ_START_HOUR		= 40,	//帮派战筛选（整点）
		PUBLIC_CONST_TYPE_RANDOM_QUEST_CD_TIME	= 41,  //环任务cd时间
		PUBLIC_CONST_TYPE_HEROCARD_EQUIPLOC_2_LEVEL = 42, // 秘籍技能第二格的开启等级
		PUBLIC_CONST_TYPE_HEROCARD_EQUIPLOC_3_LEVEL = 43, // 秘籍技能第三格的开启等级
		PUBLIC_CONST_TYPE_HEROCARD_EQUIPLOC_2_ITEM = 44, // 秘籍技能第二格所需的开启道具ID
		PUBLIC_CONST_TYPE_HEROCARD_EQUIPLOC_3_ITEM = 45, // 秘籍技能第三格所需的开启道具ID
		PUBLIC_CONST_TYPE_BAGCOST_ITEM_COIN = 46,		// 元宝对应背包扩充符比例
		PUBLIC_CONST_TYPE_DISMISSNOTICE_GUILD_HOUR = 47,	// 帮派解散通知提醒时间，小时

		PUBLIC_CONST_TYPE_RENAME_ITEM = 49, // 改名卡道具ID
		PUBLIC_CONST_TYPE_HOLYWEAPON_ENERGY_MAX = 50, // 神器能量最大值

		PUBLIC_CONST_TYPE_RUNCAR_EVERYDAY_TIMES		= 52,	//每天护送次数
		PUBLIC_CONST_TYPE_RUNCAR_MAX_DISTANCE		= 53,	//护送目标最大距离（米）

		PUBLIC_CONST_TYPE_RUNCAR_TIMEOUTSEC			= 60,	//镖车存在最大时间
		PUBLIC_CONST_TYPE_OFFLINEREWARD_COUNT_MAX = 61,	// 离线奖励最大天数
		PUBLIC_CONST_TYPE_EQUIP_STAR_NOTICE			= 62,   // 装备升星公告

		PUBLIC_CONST_TYPE_FIRE_MAP = 65, // 篝火地图
		PUBLIC_CONST_TYPE_FIRE_MAX_X = 66, // 篝火区域最大X坐标
		PUBLIC_CONST_TYPE_FIRE_MIN_X = 67, // 篝火区域最小X坐标
		PUBLIC_CONST_TYPE_FIRE_MAX_Z = 68, // 篝火区域最大Z坐标
		PUBLIC_CONST_TYPE_FIRE_MIN_Z = 69, // 篝火区域最小Z坐标
		PUBLIC_CONST_TYPE_FIRE_EXP_INTERVAL = 70, // 篝火发放经验时间间隔
		PUBLIC_CONST_TYPE_FIRE_ITEM_INTERVAL = 71, // 篝火发放道具时间间隔
		PUBLIC_CONST_TYPE_FIRE_ITEM_NOTIFY = 72, // 篝火发放道具公告ID
		PUBLIC_CONST_TYPE_FIRE_TRANSPORT_POSITION = 73, // 篝火传送坐标点
		PUBLIC_CONST_TYPE_FIRE_BEGIN_TIME = 74, // 篝火开启时间
		PUBLIC_CONST_TYPE_FIRE_END_TIME = 75, // 篝火结束时间
		PUBLIC_CONST_TYPE_FIRE_BEGIN_NOTIFYBALL = 76, // 篝火开启消息球ID
		PUBLIC_CONST_TYPE_COINS_OUTPUT_LV_PARAM = 78,	// 摇钱树铜币产量等级系数
		PUBLIC_CONST_TYPE_COINS_OUTPUT_PARAM = 79,		// 摇钱树铜币产量固定值
		PUBLIC_CONST_TYPE_COINS_RESERVES_LV_PARAM = 80, // 摇钱树铜币储量等级系数
		PUBLIC_CONST_TYPE_COINS_RESERVES_PARAM = 81,	// 摇钱树铜币储量固定值
		PUBLIC_CONST_TYPE_COINS_OUTPUT_ITEM = 82,		// 金钱露增加产量值
		PUBLIC_CONST_TYPE_COINS_RESERVES_ITEM = 83,		// 玄铁砂增加储量值
		PUBLIC_CONST_TYPE_LANS_AFFECT_HUMAN = 84,	//佣兵对主角属性值的影响
		PUBLIC_CONST_TYPE_HUMAN_AFFECT_LANS = 85,	//主角对佣兵属性值的影响
		PUBLIC_CONST_TYPE_LANS_BACK_HP_PERCENT = 89,//佣兵收回后的血量恢复百分比
		PUBLIC_CONST_TYPE_LANS_ALERT_CD_TIME   = 90,//佣兵备战位上的CD数值

		PUBLIC_CONST_TYPE_RANDSHOP_REFRESH_COUNT = 91,//家园随机商店刷新最大次数
		PUBLIC_CONST_TYPE_RANDSHOP_REFRESH_TIME = 92,//随机商店系统刷新
		PUBLIC_CONST_TYPE_LANS_SUMMON_HP_PERCENT = 93,//佣兵出战最低百分比血量

		PUBLIC_CONST_TYPE_CHALLENGE_RESETCOST = 96, //挑战 - 英雄挑战 重置次数 / 重置消耗
		PUBLIC_CONST_TYPE_CHALLENGEOTHER_RESETCOST = 97, //挑战 - 群雄挑战 重置次数 / 重置消耗

		PUBLIC_CONST_TYPE_SINGLEBOSS_STAGEID = 110,		//单人BOSS副本
		PUBLIC_CONST_TYPE_SINGLEBOSS_GREEN_TIME = 111,	//绿色CD时间
		PUBLIC_CONST_TYPE_SINGLEBOSS_BLUE_TIME = 112,	//蓝色CD时间
		PUBLIC_CONST_TYPE_SINGLEBOSS_PURPLE_TIME = 113,	//紫色CD时间
		PUBLIC_CONST_TYPE_SINGLEBOSS_GOLD_TIME = 114,	//金色CD时间

		PUBLIC_CONST_TYPE_MILITARY_1V1 = 115,		//战神1V1
		PUBLIC_CONST_TYPE_MILITARY_3V3 = 116,		//战神3V3
		PUBLIC_CONST_TYPE_MILITARY_15V15 = 117,		//战神15V15
		PUBLIC_CONST_TYPE_MILITARY_NJTZ = 118,		//战神跨服盟战

		PUBLIC_CONST_TYPE_FISH_TIME = 119,	//钓鱼时间
		PUBLIC_CONST_TYPE_EXCHANGEGIFTGOLD_VALUE = 120,		//兑换绑定元宝系数
		PUBLIC_CONST_TYPE_EXCHANGEGIFTGOLD_MIN = 121,		//单次最少兑换绑元数

		PUBLIC_CONST_TYPE_MAX,
	};

	const int32 cst_date_combin_cnt_min = 0;	// 日期次数组合最小值
	const int32 cst_date_combin_cnt_max = 99;	// 日期次数组合最大值
}

#endif // _pw_public_data_def_